import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //mainRulesSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mainRulesSidebar: [
    'intro',
    'basics',
    'creating-a-character',
    {
      type: 'category',
      label: 'Heritages',
      items: [{type: 'autogenerated', dirName: 'heritages'}],
    },
    {
      type: 'category',
      label: 'Skills',
      items: [{type: 'autogenerated', dirName: 'skills'}],
    },
    {
      type: 'category',
      label: 'Equipment',
      items: [{type: 'autogenerated', dirName: 'equipment'}],
    },
    {
      type: 'category',
      label: 'Glossary',
      items: [{type: 'autogenerated', dirName: 'glossary'}],
    },
    {
      type: 'category',
      label: 'Alchemy',
      items: [{type: 'autogenerated', dirName: 'alchemy'}],
    },
    {
      type: 'category',
      label: 'Magic',
      items: [{type: 'autogenerated', dirName: 'magic'}],
    },
    {
      type: 'category',
      label: 'Martial Arts',
      items: [{type: 'autogenerated', dirName: 'martial_arts'}],
    },
	{
		type: 'category',
		label: 'Advanced Techniques',
		items: [
			{
			type: 'category',
			label: 'Rituals',
			items: [{type: 'autogenerated', dirName: 'rituals'}],
			},
			{
			type: 'category',
			label: 'Invocations',
			items: [{type: 'autogenerated', dirName: 'invocations'}],
			},
			{
			type: 'category',
			label: 'Martial Katas',
			items: [{type: 'autogenerated', dirName: 'martial_katas'}],
			},
			{
			type: 'category',
			label: 'Interventions',
			items: [{type: 'autogenerated', dirName: 'interventions'}],
			},
		]
	},
  ],
   loreSidebar: [{type: 'autogenerated', dirName: 'lore'}]
};

export default sidebars;
