# Script for generating all the invocation pages

import os, json, math
from replacement_list import run_replaceemnt_list

# Wipe whatever is there, this folder is autogenerated
invocation_folder_path = "../docs/invocations/"


if os.path.isdir(invocation_folder_path):
	for filename in os.listdir(invocation_folder_path):
		if filename.endswith("list.mdx") and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(invocation_folder_path, filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


if os.path.isdir(os.path.join(invocation_folder_path, "invocation_descriptions")):
	for filename in os.listdir(os.path.join(invocation_folder_path, "invocation_descriptions")):
		if filename[0] != "_" and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(invocation_folder_path, "invocation_descriptions", filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


# Grab the invocation list json
invocation_contents_list = {}
with open("./Crucible_Invocations.json", "r", encoding="utf-8") as file_pointer:
	content = file_pointer.read()
	invocation_contents_list = json.loads(content)

invocation_list = []

for invocation in invocation_contents_list:
	invocation_name = invocation["Name"]
	index_of_brack = invocation_name.find("[")
	if index_of_brack > 0:
		invocation_name = invocation_name[0:index_of_brack-1]
	invocation_name = invocation_name.strip()

	invocation_path = f"../docs/invocations/invocation_descriptions/{invocation_name}.mdx"
	invocation_path = invocation_path.replace(" ", "_")
	invocation_path = invocation_path.replace(",", "")
	invocation_path = invocation_path.replace("'", "")
	invocation_path = invocation_path.replace("’", "")
	invocation_path = invocation_path.replace(" ", "_")
	invocation_path = invocation_path.lower()


	invocation_effect = invocation["Effect"]
	invocation_effect = invocation_effect.replace("<", "&lt;")
	invocation_effect = invocation_effect.replace(">", "&gt;")
	
	invocation_effect = run_replaceemnt_list(invocation_effect)

	invocation_effect = invocation_effect.replace("Affliction", "[Affliction](/docs/magic/affliction_list)")
	invocation_effect = invocation_effect.replace("Conjuration", "[Conjuration](/docs/magic/conjuration_list)")
	invocation_effect = invocation_effect.replace("Protection", "[Protection](/docs/magic/protection_list)")
	invocation_effect = invocation_effect.replace("Restoration", "[Restoration](/docs/magic/restoration_list)")
	invocation_effect = invocation_effect.replace("Transmutation", "[Transmutation](/docs/magic/transmutation_list)")


	with open(invocation_path, "w+", encoding="utf-8") as invocation_fp:
		invocation_fp.write("# " + invocation["Name"] + "\n")
		invocation_fp.write(f'<b>Type:</b> {invocation["Type"]}<br/>\n')
		invocation_fp.write(f'<b>Duration:</b> {invocation["Duration"]}<br/>\n')
		invocation_fp.write(f'<b>Effect:</b> {invocation_effect}<br/>\n\n')

	invocation_obj = (invocation_name, invocation["Type"], invocation_path)

	invocation_list.append(invocation_obj)
# Sort the invocation alphabetically
def invocation_sorter(invocation):
	return invocation[0]

with open(f"../docs/invocations/invocation_list.mdx", "w+", encoding="utf-8") as list_fp:
	list_fp.write(f"---\nsidebar_position: 2\nhide_table_of_contents: true\n---\n")
	list_fp.write(f"# Invocation List\n")
	list_fp.write("<table style={{fontSize: \'14px\', textAlign: \'center\'}}><tr><th>Invocation Name</th><th>Alchemy</th><th>Magic</th><th>Smithing</th></tr>")
	for index, invocation in enumerate(invocation_list):
		list_fp.write(f"<tr><td>[{invocation[0]}](../{invocation[2]})</td><td>{"✓" if "Alchemy" in invocation[1] else ""}</td><td>{"✓" if "Magic" in invocation[1] else ""}</td><td>{"✓" if "Smithing" in invocation[1] else ""}</td></tr>")
	list_fp.write("</table>\n")