# Script for generating all the intervention pages

import os, json, math
from replacement_list import run_replaceemnt_list

# Wipe whatever is there, this folder is autogenerated
intervention_folder_path = "../docs/interventions/"


if os.path.isdir(intervention_folder_path):
	for filename in os.listdir(intervention_folder_path):
		if filename.endswith("list.mdx") and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(intervention_folder_path, filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


if os.path.isdir(os.path.join(intervention_folder_path, "intervention_descriptions")):
	for filename in os.listdir(os.path.join(intervention_folder_path, "intervention_descriptions")):
		if filename[0] != "_" and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(intervention_folder_path, "intervention_descriptions", filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


# Grab the intervention list json
intervention_contents_list = {}
with open("./Crucible_interventions.json", "r", encoding="utf-8") as file_pointer:
	content = file_pointer.read()
	intervention_contents_list = json.loads(content)

intervention_list = []

for intervention in intervention_contents_list:
	intervention_name = intervention["Name"]
	index_of_brack = intervention_name.find("[")
	if index_of_brack > 0:
		intervention_name = intervention_name[0:index_of_brack-1]
	intervention_name = intervention_name.strip()

	intervention_path = f"../docs/interventions/intervention_descriptions/{intervention_name}.mdx"
	intervention_path = intervention_path.replace(" ", "_")
	intervention_path = intervention_path.replace(",", "")
	intervention_path = intervention_path.replace("'", "")
	intervention_path = intervention_path.replace("’", "")
	intervention_path = intervention_path.replace(" ", "_")


	intervention_benefit = intervention["Benefit"]
	intervention_benefit = intervention_benefit.replace("<", "&lt;")
	intervention_benefit = intervention_benefit.replace(">", "&gt;")
	
	intervention_benefit = run_replaceemnt_list(intervention_benefit)

	intervention_benefit = intervention_benefit.replace("Affliction School of Magic", "[Affliction School of Magic](/docs/magic/spellcasting#school)")
	intervention_benefit = intervention_benefit.replace("Conjuration School of Magic", "[Conjuration School of Magic](/docs/magic/spellcasting#school)")
	intervention_benefit = intervention_benefit.replace("Protection School of Magic", "[Protection School of Magic](/docs/magic/spellcasting#school)")
	intervention_benefit = intervention_benefit.replace("Restoration School of Magic", "[Restoration School of Magic](/docs/magic/spellcasting#school)")
	intervention_benefit = intervention_benefit.replace("Transmutation School of Magic", "[Transmutation School of Magic](/docs/magic/spellcasting#school)")


	with open(intervention_path, "w+", encoding="utf-8") as intervention_fp:
		intervention_fp.write("# " + intervention["Name"] + "\n")
		intervention_fp.write(f'<b>Type:</b> {intervention["Type"]}<br/>\n')
		intervention_fp.write(f'<b>Benefit:</b> {intervention_benefit}<br/>\n\n')

	types = intervention["Type"]
	match intervention_name:
		case "Beacon of Hope":
			types += ", Restoration"
		case "Collapsing Cosmos" | "Phoenix Flame" | "Shadow Walk":
			types += ", Affliction, Conjuration, Protection, Transmutation, Restoration"
		case "Elemental Annihilation":
			types += ", Conjuration"
		case "Feast of Souls":
			types += ", Affliction"
		case "Time Stop":
			types += ", Transmutation"
		case "Warding Shell":
			types += ", Protection"

	intervention_obj = (intervention_name, types, intervention_path)

	intervention_list.append(intervention_obj)
# Sort the intervention alphabetically
def intervention_sorter(intervention):
	return intervention[0]

with open(f"../docs/interventions/intervention_list.mdx", "w+", encoding="utf-8") as list_fp:
	list_fp.write(f"---\nsidebar_position: 2\nhide_table_of_contents: true\n---\n")
	list_fp.write(f"# Intervention List\n")
	list_fp.write("<table style={{fontSize: \'14px\', textAlign: \'center\'}}><tr><th>Intervention Name</th><th>Magical</th><th>Aff</th><th>Conj</th><th>Prot</th><th>Rest</th><th>Tra</th><th>Martial</th><th>Shadow</th><th>Crafting</th></tr>")
	for index, intervention in enumerate(intervention_list):
		list_fp.write(f"<tr><td>[{intervention[0]}](../{intervention[2]})</td><td>{"✓" if "Magical" in intervention[1] else ""}</td><td>{"✓" if "Affliction" in intervention[1] else ""}</td><td>{"✓" if "Conjuration" in intervention[1] else ""}</td><td>{"✓" if "Protection" in intervention[1] else ""}</td><td>{"✓" if "Restoration" in intervention[1] else ""}</td><td>{"✓" if "Transmutation" in intervention[1] else ""}</td><td>{"✓" if "Martial" in intervention[1] else ""}</td><td>{"✓" if "Shadow" in intervention[1] else ""}</td><td>{"✓" if "Crafting" in intervention[1] else ""}</td></tr>")
	list_fp.write("</table>\n")