# Script for generating all the alchemy pages
# Didnt want to do this all manually so using Ming's json extract

import os, json, math
from replacement_list import try_replace, replacement_list

# Wipe whatever is there, this folder is autogenerated
alchemy_folder_path = "../docs/alchemy/"


if os.path.isdir(alchemy_folder_path):
    for filename in os.listdir(alchemy_folder_path):
        if filename[0].endswith("list.mdx"):
            file_path = os.path.join(alchemy_folder_path, filename)
            if os.path.isfile(file_path):
                os.remove(file_path)


if os.path.isdir(os.path.join(alchemy_folder_path, "alchemy_descriptions")):
    for filename in os.listdir(os.path.join(alchemy_folder_path, "alchemy_descriptions")):
        if filename[0] != "_":
            file_path = os.path.join(alchemy_folder_path, "alchemy_descriptions", filename)
            if os.path.isfile(file_path):
                os.remove(file_path)


# Grab the alchemy list json
alchemy_contents_list = {}
with open("./Crucible_Alchemies.json", "r", encoding="utf-8") as file_pointer:
    content = file_pointer.read()
    alchemy_contents_list = json.loads(content)

alchemy_list = []

for alchemy in alchemy_contents_list:
    alchemy_name = alchemy["Name"]
    index_of_brack = alchemy_name.find("[")
    if index_of_brack > 0:
        alchemy_name = alchemy_name[0:index_of_brack-1]
    alchemy_name = alchemy_name.strip()

    alchemy_path = f"../docs/alchemy/alchemy_descriptions/{alchemy_name.replace("/", "_")}.mdx"
    alchemy_path = alchemy_path.replace(",", "")
    alchemy_path = alchemy_path.replace("'", "")
    alchemy_path = alchemy_path.replace("’", "")
    alchemy_path = alchemy_path.replace(" ", "_")


    alchemy_effect = alchemy["Effect"]
    alchemy_dv = alchemy["Delivery Verbal"]

    alchemy_dv = alchemy_dv.replace("<", "&lt;")
    alchemy_dv = alchemy_dv.replace(">", "&gt;")
    alchemy_effect = alchemy_effect.replace("<", "&lt;")
    alchemy_effect = alchemy_effect.replace(">", "&gt;")
    
    for needle in replacement_list:
        # If the needle is in the, but not in a tag already
        alchemy_effect = try_replace(alchemy_effect, needle)
        alchemy_dv = try_replace(alchemy_dv, needle)

    school_string = alchemy["School"]
    school_string = school_string.replace("Alchemy", "[Alchemy](../alchemy_list)")

    with open(alchemy_path, "w+", encoding="utf-8") as alchemy_fp:
        alchemy_fp.write("# " + alchemy["Name"] +"\n")
        alchemy_fp.write(f"<b>School:</b> {school_string}<br/>\n")
        alchemy_fp.write(f"<b>Level:</b> {alchemy["Level"]}<br/>\n")
        alchemy_fp.write(f"<b>Range:</b> {alchemy["Range"]}<br/>\n")
        alchemy_fp.write(f"<b>Duration:</b> {alchemy["Duration"]}<br/>\n")
        alchemy_fp.write(f"<b>Effect:</b> {alchemy_effect}<br/>\n")
        alchemy_fp.write(f"<b>[Delivery Verbal](/docs/glossary/delivery-verbal):</b> {alchemy_dv}<br/>\n")

    alchemy_obj = (alchemy_name, alchemy["Level"], alchemy["Range"], alchemy["Incantation"], alchemy_dv, alchemy_path)

    alchemy_list.append(alchemy_obj)
# Sort the alchemy first by level then alphabetically
def alchemy_sorter(alchemy):
    return alchemy[1] + alchemy[0]

with open(f"../docs/alchemy/alchemy_list.mdx", "w+", encoding="utf-8") as list_fp:
    list_fp.write(f"---\nsidebar_position: 2\nhide_table_of_contents: true\n---\n")
    list_fp.write(f"# Alchemy List\n")
    list_fp.write("<table style={{fontSize: \'14px\'}}><tr><th>Level</th><th>alchemy Name</th><th>Range</th><th>Delivery Verbal</th></tr>")
    for index, alchemy in enumerate(alchemy_list):
        color = "background: \'#E0E0E0\'" if math.floor(index/5)%2 == 1 else "background: \'#F8F8F8\'"
        list_fp.write(f"<tr style={{{{{color}}}}}><td>{alchemy[1]}</td><td>[{alchemy[0]}](../{alchemy[5]})</td><td>{alchemy[2]}</td><td>{alchemy[4]}</td></tr>")
    list_fp.write("</table>")