# Script for generating all the martial_art pages
# Didnt want to do this all manually so using Ming's json extract

import os, json, math
from replacement_list import run_replaceemnt_list

# Wipe whatever is there, this folder is autogenerated
martial_art_folder_path = "../docs/martial_arts/"


if os.path.isdir(martial_art_folder_path):
	for filename in os.listdir(martial_art_folder_path):
		if filename[0].endswith("list.mdx"):
			file_path = os.path.join(martial_art_folder_path, filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


if os.path.isdir(os.path.join(martial_art_folder_path, "martial_arts_descriptions")):
	for filename in os.listdir(os.path.join(martial_art_folder_path, "martial_arts_descriptions")):
		if filename[0] != "_":
			file_path = os.path.join(martial_art_folder_path, "martial_arts_descriptions", filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


# Grab the martial_art list json
martial_art_list = {}
with open("./Crucible_martial_arts.json", "r", encoding="utf-8") as file_pointer:
	content = file_pointer.read()
	martial_art_list = json.loads(content)

duelist_martial_arts = []
guardian_martial_arts = []
slayer_martial_arts = []

for martial_art in martial_art_list:
	martial_art_name = martial_art["Name"]
	index_of_brack = martial_art_name.find("[")
	if index_of_brack > 0:
		martial_art_name = martial_art_name[0:index_of_brack-1]
	martial_art_name = martial_art_name.strip()

	martial_art_path = f"../docs/martial_arts/martial_arts_descriptions/{martial_art_name.replace(" ", "_")}.mdx"
	martial_art_path = martial_art_path.replace(",", "")
	martial_art_path = martial_art_path.replace("'", "")
	martial_art_path = martial_art_path.replace("’", "")


	martial_art_effect = martial_art["Effect"]
	martial_art_dv = martial_art["Delivery Verbal"]

	martial_art_dv = martial_art_dv.replace("<", "&lt;")
	martial_art_dv = martial_art_dv.replace(">", "&gt;")
	martial_art_effect = martial_art_effect.replace("<", "&lt;")
	martial_art_effect = martial_art_effect.replace(">", "&gt;")
	
	martial_art_effect = run_replaceemnt_list(martial_art_effect)
	martial_art_dv = run_replaceemnt_list(martial_art_dv)

	school_string = martial_art["School"]
	school_string = school_string.replace("Duelist", "[Duelist](../duelist_list)")
	school_string = school_string.replace("Guardian", "[Guardian](../guardian_list)")
	school_string = school_string.replace("Slayer", "[Slayer](../slayer_list)")

	with open(martial_art_path, "w+", encoding="utf-8") as martial_art_fp:
		martial_art_fp.write("# " + martial_art["Name"] +"\n")
		martial_art_fp.write(f"<b>School:</b> {school_string}<br/>\n")
		martial_art_fp.write(f"<b>Level:</b> {martial_art["Level"]}<br/>\n")
		martial_art_fp.write(f"<b>Range:</b> {martial_art["Range"]}<br/>\n")
		martial_art_fp.write(f"<b>Duration:</b> {martial_art["Duration"]}<br/>\n")
		martial_art_fp.write(f"<b>Effect:</b> {martial_art_effect}<br/>\n")
		martial_art_fp.write(f"<b>[Delivery Verbal](/docs/glossary/delivery-verbal):</b> {martial_art_dv}<br/>\n")

	martial_art_obj = (martial_art_name, martial_art["Level"], martial_art["Range"], martial_art_dv, martial_art_path)

	if martial_art["School"].find("Duelist") != -1:
		duelist_martial_arts.append(martial_art_obj)
	if martial_art["School"].find("Guardian") != -1:
		guardian_martial_arts.append(martial_art_obj)
	if martial_art["School"].find("Slayer") != -1:
		slayer_martial_arts.append(martial_art_obj)

# Sort the martial_arts first by level then alphabetically
def martial_art_sorter(martial_art):
	return martial_art[1] + martial_art[0]

# martial_art Lists
martial_art_lists = {
	"Duelist": (2, duelist_martial_arts),
	"Guardian": (3, guardian_martial_arts),
	"Slayer": (4, slayer_martial_arts)}

for martial_art_list in martial_art_lists:
	martial_art_lists[martial_art_list][1].sort(key=martial_art_sorter)
	with open(f"../docs/martial_arts/{martial_art_list.lower()}_list.mdx", "w+", encoding="utf-8") as list_fp:
		list_fp.write(f"---\nsidebar_position: {martial_art_lists[martial_art_list][0]}\nhide_table_of_contents: true\n---\n")
		list_fp.write(f"# {martial_art_list} Martial Art List\n")
		list_fp.write("<table style={{fontSize: \'14px\'}}><tr><th>Level</th><th>Martial Art Name</th><th>Range</th><th>Delivery Verbal</th></tr>")
		for index, martial_art in enumerate(martial_art_lists[martial_art_list][1]):
			color = "background: \'#E0E0E0\'" if math.floor(index/5)%2 == 1 else "background: \'#F8F8F8\'"
			list_fp.write(f"<tr style={{{{{color}}}}}><td>{martial_art[1]}</td><td>[{martial_art[0]}](../{martial_art[4]})</td><td>{martial_art[2]}</td><td>{martial_art[3]}</td></tr>")
		list_fp.write("</table>")