# Script for generating all the skill pages
# Didnt want to do this all manually so using Ming's json extract

import os, json, math
from replacement_list import try_replace, replacement_list

# Wipe whatever is there, this folder is autogenerated
skill_folder_path = "../docs/new_skills/"

def remove_all (path):
    if os.path.isdir(path):
        for filename in os.listdir(path):
            if filename[0] != "_" and filename.find("_nauto") != -1:
                file_path = os.path.join(path, filename)
                if os.path.isfile(file_path):
                    os.remove(file_path)
                    
remove_all(skill_folder_path)
remove_all(os.path.join(skill_folder_path, "fighting"))
remove_all(os.path.join(skill_folder_path, "expertise"))
remove_all(os.path.join(skill_folder_path, "magic"))
remove_all(os.path.join(skill_folder_path, "crafting"))
remove_all(os.path.join(skill_folder_path, "background"))
remove_all(os.path.join(skill_folder_path, "heritage"))

fighting_skills = []
expertise_skills = []
magic_skills = []
crafting_skills = []
background_skills = []
heritage_skills = []

# Turn a single skill into a set of 10 (9 + summary) slot entries in the list
def slottify(skill):
    tr = ""
    costs = [2, 3, 4, 5]
    for level in range(1,10):
        if level == 6:
            costs = [4, 6, 8, 10]
        if skill[0] == "Martial Arts Slot":
            tr += f"<tr><td>[Level {level} {skill[0]}]({skill[4]}){"\\*" if skill[2] else ""}</td><td>{costs[0]}</td><td>{costs[1]}</td><td>{costs[2]}</td><td>{costs[3]}</td><td>[Δ](/docs/glossary/pyramid), [Weapon Training](/docs/new_skills/fighting/Weapon_Training.mdx) {round(math.ceil(level/3))} or [Stealth Training](/docs/new_skills/expertise/Stealth_Training.mdx) {math.ceil(level/3)}</td></tr>"
        else:
            tr += f"<tr><td>[Level {level} {skill[0]}]({skill[4]}){"\\*" if skill[2] else ""}</td><td>{costs[0]}</td><td>{costs[1]}</td><td>{costs[2]}</td><td>{costs[3]}</td><td>{skill[5] if level == 1 else "[Δ](/docs/glossary/pyramid)"}</td></tr>"
    tr += f"<tr><td>Cost per Column</td><td>26</td><td>39</td><td>52</td><td>78</td><td>(Not a Skill. Entry for Reference Purposes)</td></tr>"
    return tr


# Grab the skill list json
skill_contents_list = {}
with open("./Crucible_Skills.json", "r", encoding="utf-8") as file_pointer:
    content = file_pointer.read()
    skill_contents_list = json.loads(content)

skill_list = []

for skill in skill_contents_list:
    skill_name = skill["Name"]
    skill_name = skill_name.strip()

    skill_type = ""
    if "Heritage" in skill["Groups"]:
        skill_type = "Heritage"
    elif "Background" in skill["Groups"]:
        skill_type = "Background"
    elif "Fighting" in skill["Groups"]:
        skill_type = "Fighting"
    elif "Expertise" in skill["Groups"]:
        skill_type = "Expertise"
    elif "Magic" in skill["Groups"]:
        skill_type = "Magic"
    elif "Crafting" in skill["Groups"]:
        skill_type = "Crafting"

    skill_path = f"/docs/new_skills/{skill_type.lower()}/{skill_name.replace("/", "_")}.mdx"
    skill_path = skill_path.replace(",", "")
    skill_path = skill_path.replace("'", "")
    skill_path = skill_path.replace("’", "")
    skill_path = skill_path.replace(" ", "_")

    skill_benefit = skill["Benefit"]
    skill_benefit = skill_benefit.replace("<", "&lt;")
    skill_benefit = skill_benefit.replace(">", "&gt;")

    
    for needle in replacement_list:
        # If the needle is in the, but not in a tag already
        skill_benefit = try_replace(skill_benefit, needle)

    # Messy little thing to make skills link to their pre-reqs
    if skill["Requirements"] != "":
        req = skill["Requirements"]
        for skill_2 in skill_contents_list:
            sk2_name = skill_2["Name"]
            # Special cases
            if skill["Name"] == "Two Weapon Fighting, Superior":
                if sk2_name == "Two Weapon Fighting":
                    continue;
                elif sk2_name == "Two Weapon Fighting, Greater":
                    # Eye roll
                    sk2_name = "Greater Two Weapon Fighting"
            if sk2_name in req:
                skill_2_type = ""
                if "Heritage" in skill_2["Groups"]:
                    skill_2_type = "Heritage"
                elif "Background" in skill_2["Groups"]:
                    skill_2_type = "Background"
                elif "Fighting" in skill_2["Groups"]:
                    skill_2_type = "Fighting"
                elif "Expertise" in skill_2["Groups"]:
                    skill_2_type = "Expertise"
                elif "Magic" in skill_2["Groups"]:
                    skill_2_type = "Magic"
                elif "Crafting" in skill_2["Groups"]:
                    skill_2_type = "Crafting"
                skill_2_path = f"/docs/new_skills/{skill_2_type.lower()}/{skill_2["Name"].replace("/", "_")}.mdx"
                skill_2_path = skill_2_path.replace(",", "")
                skill_2_path = skill_2_path.replace("'", "")
                skill_2_path = skill_2_path.replace("’", "")
                skill_2_path = skill_2_path.replace(" ", "_")
                req = req[:req.find(sk2_name)] + "[" + sk2_name + "](" + skill_2_path + ")" + req[req.find(sk2_name) + len(sk2_name):]
        skill["Requirements"] = req


    skill_obj = (skill_name, skill["Category"], skill["Multi"], skill["Costs"], skill_path, skill["Requirements"])
    with open(".." + skill_path, "w+", encoding="utf-8") as skill_fp:
        skill_fp.write("# " + skill["Name"] +"\n")
        skill_fp.write(f"<b>Requirements:</b> {skill["Requirements"]}<br/>\n")
        skill_fp.write(f"<b>Benefit:</b> {skill_benefit}<br/>\n\n")
        if skill_type == "Heritage":
            skill_fp.write(f"<table><tr><th>Cost (SP)</th><th>With {skill["Category"]}</th><th>Without {skill["Category"]}</th></tr><tr><td>{skill_name}{"\\*" if skill["Multi"] else ""}</td><td>{skill["Costs"][0]}</td><td>{skill["Costs"][1]}</td></tr></table>\n{"*This Skill can be bought more than once\n\n" if skill["Multi"] else ""}")
            skill_fp.write(f"Category: [{skill_type}](./{skill_type.lower()}-skills), [{skill["Category"]}](/docs/heritages/heritage-traits/{skill["Category"].lower()})")
        elif skill_type == "Background":
            skill_fp.write(f"<table><tr><th>Cost (SP)</th><th>A</th><th>B</th><th>C</th><th>D</th></tr><tr><td>{skill_name}{"\\*" if skill["Multi"] else ""}</td><td>{skill["Costs"][0]}</td><td>-</td><td>-</td><td>-</td></tr></table>\n{"*This Skill can be bought more than once\n\n" if skill["Multi"] else ""}")
            skill_fp.write(f"Category: [{skill_type}](./{skill_type.lower()}-skills)")
        elif "Slot" in skill_name:
            skill_fp.write("<table><tr><th>Cost (SP)</th><th>A</th><th>B</th><th>C</th><th>D</th></tr>")
            skill_fp.write(slottify(skill_obj))
            skill_fp.write("</table>\n*This Skill can be bought more than once\n\n")
        else:
            skill_fp.write(f"<table><tr><th>Cost (SP)</th><th>A</th><th>B</th><th>C</th><th>D</th></tr><tr><td>{skill_name}{"\\*" if skill["Multi"] else ""}</td><td>{skill["Costs"][0]}</td><td>{skill["Costs"][1]}</td><td>{skill["Costs"][2]}</td><td>{skill["Costs"][3]}</td></tr></table>\n{"*This Skill can be bought more than once\n\n" if skill["Multi"] else ""}")
            skill_fp.write(f"Category: [{skill_type}](./{skill_type.lower()}-skills)")

    if skill_type == "Fighting":
        fighting_skills.append(skill_obj)
    elif skill_type == "Expertise":
        expertise_skills.append(skill_obj)
    elif skill_type == "Magic":
        magic_skills.append(skill_obj)
    elif skill_type == "Crafting":
        crafting_skills.append(skill_obj)
    elif skill_type == "Heritage":
        heritage_skills.append(skill_obj)
    elif skill_type == "Background":
        background_skills.append(skill_obj)
# Sort the skill alphabetically by category then by name with some replacements for numerals
def skill_sorter(skill):
    
    return skill[1] + skill[0].replace("First", "1").replace("Second", "2").replace("Third", "3").replace("Fourth", "4").replace("Fifth", "5")

skill_lists = {
    "Fighting": (2, fighting_skills),
    "Expertise": (3, expertise_skills),
    "Magic": (4, magic_skills),
    "Crafting": (5, crafting_skills),
    "Heritage": (6, heritage_skills),
    "Background": (7, background_skills)
}

current_categ = ""

for skill_list in skill_lists:
    skill_lists[skill_list][1].sort(key=skill_sorter)
    with open(f"../docs/new_skills/{skill_list.lower()}/{skill_list.lower()}-skills.mdx", "w+", encoding="utf-8") as list_fp:
        list_fp.write(f"---\nsidebar_position: {skill_lists[skill_list][0]}\nhide_table_of_contents: true\n---\n")
        list_fp.write(f"# {skill_list} Skill List\n")
        if skill_list != "Heritage" and skill_list != "Background":
            list_fp.write("<table style={{fontSize: \'14px\', padding: \'2px\'}}><tr><th>Skill Name</th><th>A</th><th>B</th><th>C</th><th>D</th><th>Pre-Requisite(s)</th></tr>")
            for index, skill in enumerate(skill_lists[skill_list][1]):
                if current_categ != skill[1]:
                    list_fp.write(f"<tr><td><b>{skill[1]}</b></td><td></td><td></td><td></td><td></td><td></td></tr>")
                    current_categ = skill[1]
                if "Slot" in skill[0]:
                    # need to handle slot ones seperate
                    list_fp.write(slottify(skill))
                else:
                    list_fp.write(f"<tr><td>[{skill[0]}]({skill[4]}){"\\*" if skill[2] else ""}</td><td>{skill[3][0]}</td><td>{skill[3][1]}</td><td>{skill[3][2]}</td><td>{skill[3][3]}</td><td>{skill[5]}</td></tr>")
            list_fp.write("</table>")
        elif skill_list == "Heritage":
            list_fp.write("<table style={{fontSize: \'14px\', padding: \'2px\'}}><tr><th>Skill Name</th><th>Has Trait</th><th>Does Not Have Trait</th><th>Pre-Requisite(s)</th></tr>")
            for index, skill in enumerate(skill_lists[skill_list][1]):
                if current_categ != skill[1]:
                    list_fp.write(f"<tr><td><b>[{skill[1]}](/docs/heritages/heritage-traits/{skill[1].lower()})</b></td><td></td><td></td><td></td></tr>")
                    current_categ = skill[1]
                list_fp.write(f"<tr><td>[{skill[0]}]({skill[4]}{"\\*" if skill[2] else ""})</td><td>{skill[3][0]}</td><td>{skill[3][1]}</td><td>{skill[5]}</td></tr>")
            list_fp.write("</table>")
        elif skill_list == "Background":
            list_fp.write("<table style={{fontSize: \'14px\', padding: \'2px\'}}><tr><th>Skill Name</th><th>A</th><th>B</th><th>C</th><th>D</th><th>Pre-Requisite(s)</th></tr>")
            for index, skill in enumerate(skill_lists[skill_list][1]):
                if current_categ != skill[1]:
                    list_fp.write(f"<tr><td><b>{skill[1]}</b></td><td></td><td></td><td></td><td></td><td></td></tr>")
                    current_categ = skill[1]
                list_fp.write(f"<tr><td>[{skill[0]}]({skill[4]}{"\\*" if skill[2] else ""})</td><td>{skill[3][0]}</td><td>-</td><td>-</td><td>-</td><td>{skill[5]}</td></tr>")
            list_fp.write("</table>")
        list_fp.write("\n*This Skill can be bought more than once")