# Script for generating all the martial_kata pages

import os, json, math
from replacement_list import run_replaceemnt_list

# Wipe whatever is there, this folder is autogenerated
martial_kata_folder_path = "../docs/martial_katas/"


if os.path.isdir(martial_kata_folder_path):
	for filename in os.listdir(martial_kata_folder_path):
		if filename.endswith("list.mdx") and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(martial_kata_folder_path, filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


if os.path.isdir(os.path.join(martial_kata_folder_path, "martial_kata_descriptions")):
	for filename in os.listdir(os.path.join(martial_kata_folder_path, "martial_kata_descriptions")):
		if filename[0] != "_" and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(martial_kata_folder_path, "martial_kata_descriptions", filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


# Grab the martial_kata list json
martial_kata_contents_list = {}
with open("./Crucible_martial_katas.json", "r", encoding="utf-8") as file_pointer:
	content = file_pointer.read()
	martial_kata_contents_list = json.loads(content)

martial_kata_list = []

for martial_kata in martial_kata_contents_list:
	martial_kata_name = martial_kata["Name"]
	index_of_brack = martial_kata_name.find("[")
	if index_of_brack > 0:
		martial_kata_name = martial_kata_name[0:index_of_brack-1]
	martial_kata_name = martial_kata_name.strip()

	martial_kata_path = f"../docs/martial_katas/martial_kata_descriptions/{martial_kata_name}.mdx"
	martial_kata_path = martial_kata_path.replace(" ", "_")
	martial_kata_path = martial_kata_path.replace(",", "")
	martial_kata_path = martial_kata_path.replace("'", "")
	martial_kata_path = martial_kata_path.replace("’", "")
	martial_kata_path = martial_kata_path.replace(" ", "_")
	martial_kata_path = martial_kata_path.lower()


	martial_kata_effect = martial_kata["Effect"]
	martial_kata_effect = martial_kata_effect.replace("<", "&lt;")
	martial_kata_effect = martial_kata_effect.replace(">", "&gt;")
	
	martial_kata_effect = run_replaceemnt_list(martial_kata_effect)

	martial_kata_school = martial_kata['School']

	martial_kata_school = martial_kata_school.replace("Guardian", "[Guardian](/docs/martial_arts/guardian_list)")
	martial_kata_school = martial_kata_school.replace("Duelist", "[Duelist](/docs/martial_arts/duelist_list)")
	martial_kata_school = martial_kata_school.replace("Slayer", "[Slayer](/docs/martial_arts/slayer_list)")


	with open(martial_kata_path, "w+", encoding="utf-8") as martial_kata_fp:
		martial_kata_fp.write("# " + martial_kata["Name"] + "\n")
		martial_kata_fp.write(f'<b>School:</b> {martial_kata_school}<br/>\n')
		martial_kata_fp.write(f'<b>Effect:</b> {martial_kata_effect}<br/>\n\n')

	martial_kata_obj = (martial_kata_name, martial_kata_school, martial_kata_path)

	martial_kata_list.append(martial_kata_obj)
# Sort the martial_kata alphabetically
def martial_kata_sorter(martial_kata):
	return martial_kata[0]

with open(f"../docs/martial_katas/martial_kata_list.mdx", "w+", encoding="utf-8") as list_fp:
	list_fp.write(f"---\nsidebar_position: 2\nhide_table_of_contents: true\n---\n")
	list_fp.write(f"# Martial Kata List\n")
	list_fp.write("<table style={{fontSize: \'14px\', textAlign: \'center\'}}><tr><th>Martial Kata Name</th><th>Duelist</th><th>Guardian</th><th>Slayer</th></tr>")
	for index, martial_kata in enumerate(martial_kata_list):
		list_fp.write(f"<tr><td>[{martial_kata[0]}](../{martial_kata[2]})</td><td>{"✓" if "Duelist" in martial_kata[1] else ""}</td><td>{"✓" if "Guardian" in martial_kata[1] else ""}</td><td>{"✓" if "Slayer" in martial_kata[1] else ""}</td></tr>")
	list_fp.write("</table>\n")