# Script for generating all the spell pages
# Didnt want to do this all manually so using Ming's json extract

import os, json, math
from replacement_list import run_replaceemnt_list

# Wipe whatever is there, this folder is autogenerated
spell_folder_path = "../docs/magic/"


if os.path.isdir(spell_folder_path):
	for filename in os.listdir(spell_folder_path):
		if filename[0].endswith("list.mdx") and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(spell_folder_path, filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


if os.path.isdir(os.path.join(spell_folder_path, "spell_descriptions")):
	for filename in os.listdir(os.path.join(spell_folder_path, "spell_descriptions")):
		if filename[0] != "_" and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(spell_folder_path, "spell_descriptions", filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


# Grab the spell list json
spell_list = {}
with open("./Crucible_Spells.json", "r", encoding="utf-8") as file_pointer:
	content = file_pointer.read()
	spell_list = json.loads(content)

affliction_spells = []
conjuration_spells = []
protection_spells = []
restoration_spells = []
transmutation_spells = []

for spell in spell_list:
	spell_name = spell["Name"]
	index_of_brack = spell_name.find("[")
	if index_of_brack > 0:
		spell_name = spell_name[0:index_of_brack-1]
	spell_name = spell_name.strip()

	spell_path = f"../docs/magic/spell_descriptions/{spell_name.replace(" ", "_")}.mdx"
	spell_path = spell_path.replace(",", "")
	spell_path = spell_path.replace("'", "")
	spell_path = spell_path.replace("’", "")


	spell_effect = spell["Effect"]
	spell_dv = spell["Delivery Verbal"]

	spell_dv = spell_dv.replace("<", "&lt;")
	spell_dv = spell_dv.replace(">", "&gt;")
	spell_effect = spell_effect.replace("<", "&lt;")
	spell_effect = spell_effect.replace(">", "&gt;")
	
	spell_effect = run_replaceemnt_list(spell_effect)
	spell_dv = run_replaceemnt_list(spell_dv)

	school_string = spell["School"]
	school_string = school_string.replace("Affliction", "[Affliction](../affliction_list)")
	school_string = school_string.replace("Conjuration", "[Conjuration](../conjuration_list)")
	school_string = school_string.replace("Protection", "[Protection](../protection_list)")
	school_string = school_string.replace("Restoration", "[Restoration](../restoration_list)")
	school_string = school_string.replace("Transmutation", "[Transmutation](../transmutation_list)")

	with open(spell_path, "w+", encoding="utf-8") as spell_fp:
		spell_fp.write("# " + spell["Name"] +"\n")
		spell_fp.write(f"<b>School:</b> {school_string}<br/>\n")
		spell_fp.write(f"<b>Level:</b> {spell["Level"]}<br/>\n")
		spell_fp.write(f"<b>Range:</b> {spell["Range"]}<br/>\n")
		spell_fp.write(f"<b>Duration:</b> {spell["Duration"]}<br/>\n")
		spell_fp.write(f"<b>Effect:</b> {spell_effect}<br/>\n")
		spell_fp.write(f"<b>Incantation:</b> {spell["Incantation"]}<br/>\n")
		spell_fp.write(f"<b>[Delivery Verbal](/docs/glossary/delivery-verbal):</b> {spell_dv}<br/>\n")

	spell_obj = (spell_name, spell["Level"], spell["Range"], spell["Incantation"], spell_dv, spell_path)

	if spell["School"].find("Affliction") != -1:
		affliction_spells.append(spell_obj)
	if spell["School"].find("Conjuration") != -1:
		conjuration_spells.append(spell_obj)
	if spell["School"].find("Protection") != -1:
		protection_spells.append(spell_obj)
	if spell["School"].find("Restoration") != -1:
		restoration_spells.append(spell_obj)
	if spell["School"].find("Transmutation") != -1:
		transmutation_spells.append(spell_obj)

# Sort the spells first by level then alphabetically
def spell_sorter(spell):
	return spell[1] + spell[0]

# Spell Lists
spell_lists = {
	"Affliction": (2, affliction_spells),
	"Conjuration": (3, conjuration_spells),
	"Protection": (4, protection_spells),
	"Restoration": (5, restoration_spells),
	"Transmutation": (6, transmutation_spells)}

for spell_list in spell_lists:
	spell_lists[spell_list][1].sort(key=spell_sorter)
	with open(f"../docs/magic/{spell_list.lower()}_list.mdx", "w+", encoding="utf-8") as list_fp:
		list_fp.write(f"---\nsidebar_position: {spell_lists[spell_list][0]}\nhide_table_of_contents: true\n---\n")
		list_fp.write(f"# {spell_list} Spell List\n")
		cantrip = spell_lists[spell_list][1][0]
		list_fp.write(f"{spell_list}'s [Cantrip](./cantrips) is [{cantrip[0]}](../{cantrip[5]})\n\n")
		list_fp.write("<table style={{fontSize: \'14px\'}}><tr><th>Level</th><th>Spell Name</th><th>Range</th><th>Incantation</th><th>Delivery Verbal</th></tr>")
		for index, spell in enumerate(spell_lists[spell_list][1][1:]):
			color = "background: \'#E0E0E0\'" if math.floor(index/5)%2 == 1 else "background: \'#F8F8F8\'"
			list_fp.write(f"<tr style={{{{{color}}}}}><td>{spell[1]}</td><td>[{spell[0]}](../{spell[5]})</td><td>{spell[2]}</td><td>{spell[3]}</td><td>{spell[4]}</td></tr>")
		list_fp.write("</table>")