# Script for generating all the ritual pages

import os, json, math
from replacement_list import run_replaceemnt_list

# Rituals have lots of special terms
ritual_replacement_list = {
	"Flaw": "[Flaw](/docs/rituals/ritual_glossary#Flaw)",
	"Backlash": "[Backlash](/docs/rituals/ritual_glossary#Backlash)",
	"Catastrophe": "[Catastrophe](/docs/rituals/ritual_glossary#Catastrophe)",
	"Fail": "[Fail](/docs/rituals/ritual_glossary#Fail)",
	"Item": "[Item](/docs/rituals/ritual_glossary#Item)",
	"Spirit": "[Spirit](/docs/rituals/ritual_glossary#Spirit)",
	"Caster": "[Caster](/docs/rituals/ritual_glossary#Caster)",
	"Primary Caster": "[Primary Caster](/docs/rituals/ritual_glossary#Primary-Caster)",
	"Secondary Caster": "[Secondary Caster](/docs/rituals/ritual_glossary#Secondary-Caster)",
	"Circle": "[Circle](/docs/rituals/ritual_glossary#Circle)",
	"Protective Circle": "[Protective Circle](/docs/rituals/ritual_glossary#protective-circle)",
	"Component": "[Component](/docs/rituals/ritual_glossary#component)",
	"Special Component": "[Special Component](/docs/rituals/ritual_glossary#special-component)",
	"Concert": "[Concert](/docs/rituals/ritual_glossary#concert)",
	"Limited": "[Limited](/docs/rituals/ritual_glossary#limited)",
	"Scroll": "[Scroll](/docs/rituals/ritual_glossary#scroll)",
	"Unstable": "[Unstable](/docs/rituals/ritual_glossary#unstable)",
	"Ritual Effect Slots": "[Ritual Effect Slots](/docs/rituals/ritual_glossary#ritual-effect-slots)",
	"Slot": "[Ritual Effect Slots](/docs/rituals/ritual_glossary#ritual-effect-slots)",
}

# Wipe whatever is there, this folder is autogenerated
ritual_folder_path = "../docs/rituals/"


if os.path.isdir(ritual_folder_path):
	for filename in os.listdir(ritual_folder_path):
		if filename.endswith("list.mdx") and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(ritual_folder_path, filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


if os.path.isdir(os.path.join(ritual_folder_path, "ritual_descriptions")):
	for filename in os.listdir(os.path.join(ritual_folder_path, "ritual_descriptions")):
		if filename[0] != "_" and filename[0] != "_" and "nauto" not in filename:
			file_path = os.path.join(ritual_folder_path, "ritual_descriptions", filename)
			if os.path.isfile(file_path):
				os.remove(file_path)


# Grab the ritual list json
ritual_contents_list = {}
with open("./Crucible_Rituals.json", "r", encoding="utf-8") as file_pointer:
	content = file_pointer.read()
	ritual_contents_list = json.loads(content)

ritual_list = []

for ritual in ritual_contents_list:
	ritual_name = ritual["Name"]
	index_of_brack = ritual_name.find("[")
	if index_of_brack > 0:
		ritual_name = ritual_name[0:index_of_brack-1]
	ritual_name = ritual_name.strip()

	ritual_path = f"../docs/rituals/ritual_descriptions/{ritual_name}.mdx"
	ritual_path = ritual_path.replace(" ", "_")
	ritual_path = ritual_path.replace(",", "")
	ritual_path = ritual_path.replace("'", "")
	ritual_path = ritual_path.replace("’", "")
	ritual_path = ritual_path.replace(" ", "_")
	ritual_path = ritual_path.lower()


	ritual_effect = ritual["Effect"]
	ritual_effect = ritual_effect.replace("<", "&lt;")
	ritual_effect = ritual_effect.replace(">", "&gt;")
	
	ritual_effect = run_replaceemnt_list(ritual_effect, override_list=ritual_replacement_list)
	ritual_effect = run_replaceemnt_list(ritual_effect)

	school_string = ritual["School"]
	school_string = school_string.replace("Affliction", "[Affliction](/docs/magic/affliction_list)")
	school_string = school_string.replace("Conjuration", "[Conjuration](/docs/magic/conjuration_list)")
	school_string = school_string.replace("Protection", "[Protection](/docs/magic/protection_list)")
	school_string = school_string.replace("Restoration", "[Restoration](/docs/magic/restoration_list)")
	school_string = school_string.replace("Transmutation", "[Transmutation](/docs/magic/transmutation_list)")


	with open(ritual_path, "w+", encoding="utf-8") as ritual_fp:
		ritual_fp.write("# " + ritual["Name"] + "\n")
		ritual_fp.write(f'<b>Cost:</b> {ritual["Cost"]}<br/>\n')
		ritual_fp.write(f'<b>Type:</b> {ritual["Type"]}<br/>\n')
		ritual_fp.write(f'<b>School:</b> {school_string}<br/>\n')
		ritual_fp.write(f'<b>Target:</b> {ritual["Target"]}<br/>\n')
		ritual_fp.write(f'<b>Duration:</b> {ritual["Duration"]}<br/>\n')
		ritual_fp.write(f'<b>Effect:</b> {ritual_effect}<br/>\n\n')
		if ritual["Multi"]:
			ritual_fp.write('This Ritual can be cast on a target more than once\n')

	if ritual_name == "Channel Spell" or ritual_name == "Imbue Spell":
		ritual["School"] = "Affliction, Conjuration, Protection, Restoration, Transmutation"
	elif ritual_name == "Duplicate Scroll" or ritual_name == "Instill Chaos":
		ritual["School"] = "Affliction, Conjuration, Protection, Restoration, Transmutation"
		ritual["Type"] = "Alchemy, Smithing"
	elif ritual_name == "Spell Bond":
		ritual["School"] = "Affliction, Conjuration, Protection, Restoration, Transmutation"
		ritual["Type"] = "Smithing"


	ritual_obj = (ritual_name, ritual["Multi"], ritual["Groups"], ritual["Type"], ritual["School"], ritual["Cost"], ritual_path)

	ritual_list.append(ritual_obj)
# Sort the ritual alphabetically
def ritual_sorter(ritual):
	return ritual[0]

with open(f"../docs/rituals/ritual_list.mdx", "w+", encoding="utf-8") as list_fp:
	list_fp.write(f"---\nsidebar_position: 2\nhide_table_of_contents: true\n---\n")
	list_fp.write(f"# Ritual List\n")
	list_fp.write("<table style={{fontSize: \'14px\', textAlign: \'center\'}}><tr><th>Ritual Name</th><th>Limited?</th><th>A</th><th>C</th><th>P</th><th>R</th><th>T</th><th>Alchemy</th><th>Smithing</th><th>Ritual Cost</th></tr>")
	for index, ritual in enumerate(ritual_list):
		list_fp.write(f"<tr><td>[{ritual[0]}](../{ritual[6]}){"\\*" if ritual[1] else ""}</td><td>{"Yes" if "Limited" in ritual[2] else ""}</td><td>{"✓" if "Affliction" in ritual[4] else ""}</td><td>{"✓" if "Conjuration" in ritual[4] else ""}</td><td>{"✓" if "Protection" in ritual[4] else ""}</td><td>{"✓" if "Restoration" in ritual[4] else ""}</td><td>{"✓" if "Transmutation" in ritual[4] else ""}</td><td>{"✓" if "Alchemy" in ritual[3] else ""}</td><td>{"✓" if "Smithing" in ritual[3] else ""}</td><td>{ritual[5]}</td></tr>")
	list_fp.write("</table>\n")
	list_fp.write("*Rituals marked with a \"\\*\" can be cast on a target more than once.\n\n")
	list_fp.write("If a Ritual has multiple Schools listed the Caster only needs access to one, and only if casting with Ritual Magic.")