Could not find skill alchemical slot
Could not find skill martial arts slot
Could not find skill spell slot
/docs/skills/magic/Absorb_Magic.mdx
/docs/skills/crafting/Absorb_Poison.mdx
/docs/skills/background/Academic.mdx
Adding static content from ../docs/skills/background/_Academic.mdx to ../docs/skills/background/Academic.mdx
/docs/skills/expertise/Acid_Bomb.mdx
/docs/skills/expertise/Acid_Grenade.mdx
/docs/skills/expertise/Acid_Trap.mdx
/docs/skills/crafting/Alchemical_Tradition.mdx
/docs/skills/crafting/Alchemical_Slot.mdx
/docs/skills/crafting/Alkahestry.mdx
/docs/skills/heritage/Ambush.mdx
/docs/skills/magic/Arcane_Armour.mdx
/docs/skills/fighting/Archery.mdx
/docs/skills/fighting/Armour_Mastery.mdx
/docs/skills/crafting/Augment_Potion.mdx
/docs/skills/crafting/Augment_Scroll.mdx
/docs/skills/expertise/Avoidance_Armour.mdx
/docs/skills/fighting/Axe_Mastery.mdx
/docs/skills/background/Bodyguard.mdx
/docs/skills/heritage/Break_Compulsion.mdx
/docs/skills/crafting/Catalyst.mdx
/docs/skills/magic/Channel_Spell.mdx
/docs/skills/crafting/Chemistry.mdx
/docs/skills/crafting/Contingent_Slime.mdx
/docs/skills/magic/Contingent_Spell.mdx
/docs/skills/fighting/Counter.mdx
/docs/skills/crafting/Create_Cauldron.mdx
/docs/skills/crafting/Create_Flask.mdx
/docs/skills/crafting/Create_Potion.mdx
/docs/skills/crafting/Create_Scroll.mdx
/docs/skills/crafting/Create_Wand.mdx
/docs/skills/expertise/Deadly_Strike.mdx
/docs/skills/expertise/Defensive_Roll.mdx
/docs/skills/background/Diagnose.mdx
/docs/skills/heritage/Die_Hard.mdx
/docs/skills/heritage/Disrupt_Magic.mdx
/docs/skills/expertise/Dodge.mdx
/docs/skills/crafting/Echo_Slime.mdx
/docs/skills/magic/Echo_Spell.mdx
/docs/skills/magic/Empower_Spell.mdx
/docs/skills/crafting/Envenom_Weapon.mdx
/docs/skills/crafting/Envenom_Weapon_Greater.mdx
/docs/skills/crafting/Envenom_Weapon_Superior.mdx
/docs/skills/heritage/Escape_Binding.mdx
/docs/skills/expertise/Evasion.mdx
/docs/skills/expertise/Expert_Combatant.mdx
/docs/skills/expertise/Expose_Weakness.mdx
/docs/skills/expertise/Extra_Trap.mdx
/docs/skills/background/Favoured_By_Destiny.mdx
/docs/skills/heritage/Field_Repair.mdx
/docs/skills/heritage/Fieldwork.mdx
/docs/skills/magic/Fifth_School_of_Magic.mdx
/docs/skills/expertise/Fire_Bomb.mdx
/docs/skills/expertise/Fire_Grenade.mdx
/docs/skills/expertise/Fire_Trap.mdx
/docs/skills/background/First_Aid.mdx
/docs/skills/fighting/First_Martial_Arts_School.mdx
/docs/skills/magic/First_School_of_Magic.mdx
/docs/skills/expertise/Flanking.mdx
/docs/skills/fighting/Florentine.mdx
/docs/skills/heritage/Focus.mdx
/docs/skills/magic/Fourth_School_of_Magic.mdx
/docs/skills/expertise/Freezing_Bomb.mdx
/docs/skills/expertise/Freezing_Grenade.mdx
/docs/skills/expertise/Freezing_Trap.mdx
/docs/skills/heritage/Frenzy.mdx
/docs/skills/expertise/Giant_Trap.mdx
/docs/skills/magic/Harden_Magic.mdx
/docs/skills/heritage/Harvester.mdx
/docs/skills/magic/Innate_Spellcasting.mdx
/docs/skills/magic/Innate_Spellcasting_Greater.mdx
/docs/skills/magic/Innate_Spellcasting_Superior.mdx
/docs/skills/background/Invoker.mdx
/docs/skills/heritage/Last_Words.mdx
/docs/skills/crafting/Legendary_Invention.mdx
/docs/skills/heritage/Lifebind.mdx
/docs/skills/fighting/Long_Axe.mdx
/docs/skills/fighting/Long_Mace.mdx
/docs/skills/fighting/Long_Mastery.mdx
/docs/skills/fighting/Long_Sword.mdx
/docs/skills/fighting/Mace_Mastery.mdx
/docs/skills/magic/Magical_Aptitude.mdx
/docs/skills/magic/Magical_Intervention.mdx
/docs/skills/magic/Magical_Tradition.mdx
/docs/skills/fighting/Martial_Arts_Slot.mdx
/docs/skills/fighting/Martial_Intervention.mdx
/docs/skills/fighting/Martial_Kata.mdx
/docs/skills/fighting/Martial_Secret.mdx
/docs/skills/fighting/Martial_Tradition.mdx
/docs/skills/crafting/Master_Alchemist.mdx
/docs/skills/magic/Master_Ritualist.mdx
/docs/skills/crafting/Masters_Secret.mdx
/docs/skills/crafting/Memorise_Recipe.mdx
/docs/skills/magic/Memorise_Ritual.mdx
/docs/skills/heritage/Mercantile_Connections.mdx
/docs/skills/background/Merchant.mdx
/docs/skills/heritage/Mind_Over_Body.mdx
/docs/skills/crafting/Mix_Poison.mdx
/docs/skills/heritage/Natural_Cunning.mdx
/docs/skills/heritage/Natural_Dodge.mdx
/docs/skills/heritage/Natural_Fortification.mdx
/docs/skills/heritage/Natural_Magic.mdx
/docs/skills/heritage/Natural_Parry.mdx
/docs/skills/heritage/Natural_Remedy.mdx
/docs/skills/heritage/Natural_Ritualist.mdx
/docs/skills/heritage/Natural_Strength.mdx
/docs/skills/heritage/Natural_Toughness.mdx
/docs/skills/expertise/Open_Lock.mdx
/docs/skills/fighting/Parry.mdx
/docs/skills/fighting/Penance.mdx
/docs/skills/expertise/Penetrating_Strike.mdx
/docs/skills/background/Physician.mdx
Adding static content from ../docs/skills/background/_Physician.mdx to ../docs/skills/background/Physician.mdx
/docs/skills/crafting/Piercing_Slime.mdx
/docs/skills/magic/Piercing_Spell.mdx
/docs/skills/expertise/Precise_Strike.mdx
/docs/skills/heritage/Psychic_Awaken.mdx
/docs/skills/heritage/Psychic_Charm.mdx
/docs/skills/magic/Quicken_Spell.mdx
/docs/skills/heritage/Quickness.mdx
/docs/skills/heritage/Rapid_Refit:_Avoidance.mdx
/docs/skills/background/Read_and_Write.mdx
/docs/skills/heritage/Resist_Break.mdx
/docs/skills/heritage/Resist_Compulsion.mdx
/docs/skills/heritage/Resist_Curse.mdx
/docs/skills/heritage/Resist_Fumble.mdx
/docs/skills/heritage/Resist_Magic.mdx
/docs/skills/heritage/Resist_Physical.mdx
/docs/skills/heritage/Resist_Poison.mdx
/docs/skills/magic/Ritual_Magic.mdx
/docs/skills/crafting/Rune_Carving.mdx
/docs/skills/background/Sailor.mdx
/docs/skills/fighting/Savage_Strike.mdx
/docs/skills/fighting/Second_Martial_Arts_School.mdx
/docs/skills/magic/Second_School_of_Magic.mdx
/docs/skills/crafting/Secret_Technique.mdx
/docs/skills/background/Seer.mdx
/docs/skills/heritage/Sense_Magic.mdx
/docs/skills/heritage/Sense_Poison.mdx
/docs/skills/expertise/Shadow_Intervention.mdx
/docs/skills/expertise/Shadow_Shot.mdx
/docs/skills/fighting/Shield.mdx
/docs/skills/fighting/Short_Axe.mdx
/docs/skills/fighting/Short_Mace.mdx
/docs/skills/fighting/Short_Mastery.mdx
/docs/skills/fighting/Short_Sword.mdx
/docs/skills/expertise/Shrapnel_Bomb.mdx
/docs/skills/expertise/Shrapnel_Grenade.mdx
/docs/skills/expertise/Shrapnel_Trap.mdx
/docs/skills/fighting/Simple_Weapon.mdx
/docs/skills/crafting/Slime_Armour.mdx
/docs/skills/crafting/Slime_Shuck.mdx
/docs/skills/crafting/Slimy_Coating.mdx
/docs/skills/crafting/Smithing.mdx
/docs/skills/crafting/Smithing_Grand_Master.mdx
/docs/skills/crafting/Smithing_Master.mdx
/docs/skills/magic/Spell_Channelling.mdx
/docs/skills/magic/Spell_Channelling_Greater.mdx
/docs/skills/magic/Spell_Channelling_Superior.mdx
/docs/skills/magic/Spell_Slot.mdx
/docs/skills/expertise/Split_Shot.mdx
/docs/skills/background/Spy.mdx
/docs/skills/fighting/Staff.mdx
/docs/skills/expertise/Stealth_Prowess.mdx
/docs/skills/expertise/Stealth_Training.mdx
/docs/skills/fighting/Style_Master.mdx
/docs/skills/fighting/Sword_Mastery.mdx
/docs/skills/crafting/Symbiont.mdx
/docs/skills/fighting/Third_Martial_Arts_School.mdx
/docs/skills/magic/Third_School_of_Magic.mdx
/docs/skills/fighting/Thrown.mdx
/docs/skills/fighting/Toughness.mdx
/docs/skills/crafting/Toxication.mdx
/docs/skills/expertise/Toxin_Bomb.mdx
/docs/skills/expertise/Toxin_Grenade.mdx
/docs/skills/expertise/Toxin_Trap.mdx
/docs/skills/expertise/Tricksters_Insight.mdx
/docs/skills/background/Trophy_Hunter.mdx
/docs/skills/fighting/Two-Handed_Axe.mdx
/docs/skills/fighting/Two-Handed_Mace.mdx
/docs/skills/fighting/Two-Handed_Mastery.mdx
/docs/skills/fighting/Two-Handed_Sword.mdx
/docs/skills/fighting/Two_Weapon_Fighting.mdx
/docs/skills/fighting/Two_Weapon_Fighting_Greater.mdx
/docs/skills/fighting/Two_Weapon_Fighting_Superior.mdx
/docs/skills/heritage/Vanish.mdx
/docs/skills/fighting/Vital_Strike.mdx
/docs/skills/heritage/Vorpal_Strike.mdx
/docs/skills/fighting/Weapon_Chain.mdx
/docs/skills/heritage/Weapon_Familiarity.mdx
/docs/skills/fighting/Weapon_Prowess.mdx
/docs/skills/fighting/Weapon_Mastery.mdx
/docs/skills/fighting/Weapon_Training.mdx
/docs/skills/fighting/Wear_Extra_Armour.mdx
